// Auctra AI - Multi-Platform Real B2B Supplier Directory & Enterprise Risk Scoring
// Connects IndiaMART, TradeIndia, Alibaba, and Amazon Business with 4-Dimensional Risk Models

export const B2B_PLATFORMS = [
  { id: "all", name: "All Sources", icon: "Globe", count: 18 },
  { id: "indiamart", name: "IndiaMART", icon: "Building", count: 6, color: "text-emerald-700 bg-emerald-50 border-emerald-200" },
  { id: "amazon_business", name: "Amazon Business", icon: "ShoppingBag", count: 4, color: "text-amber-700 bg-amber-50 border-amber-200" },
  { id: "tradeindia", name: "TradeIndia", icon: "Layers", count: 4, color: "text-blue-700 bg-blue-50 border-blue-200" },
  { id: "alibaba", name: "Alibaba Global", icon: "Compass", count: 4, color: "text-orange-700 bg-orange-50 border-orange-200" }
];

export const REAL_WORLD_SUPPLIERS = [
  // --- IndiaMART Verified Suppliers ---
  {
    id: "ven_techhub_01",
    name: "TechHub Direct",
    platform: "indiamart",
    platformLabel: "IndiaMART Star Supplier",
    platformBadgeColor: "bg-emerald-100 text-emerald-800 border-emerald-300",
    legalName: "TechHub Direct Sourcing Pvt Ltd",
    trustScore: 98,
    slaHours: 24,
    currentBid: 850,
    rating: 4.9,
    city: "Bengaluru",
    state: "Karnataka",
    isVerified: true,
    isoCertified: true,
    msmeRegistered: true,
    pastFulfillmentRate: 99.2,
    categories: ["IT Peripherals", "Ergonomics", "Electronics"],
    minLeadTimeHours: 24,
    gstin: "29AAACT9812M1Z2",
    catalogUrl: "https://www.indiamart.com/techhub-direct",
    verifiedProof: "IndiaMART TrustSEAL Verified - Star Supplier Tier 1",
    contactEmail: "contracts@techhubdirect.com",
    contactPhone: "+91 80 4122 8900",
    // Supplier Risk Scoring
    riskScore: 8, // 0 - 100, lower is safer
    riskCategory: "VERY_LOW",
    riskLabel: "Tier-1 Low Risk",
    creditRating: "AAA",
    financialHealthScore: 97,
    operationalRiskScore: 6,
    complianceRiskScore: 4,
    gstFilingHealth: "100% Timely (36 Mo)",
    litigationCheck: "Zero Active Disputes"
  },
  {
    id: "ven_voltmart_02",
    name: "VoltMart Electronics",
    platform: "indiamart",
    platformLabel: "IndiaMART Verified Exporter",
    platformBadgeColor: "bg-emerald-100 text-emerald-800 border-emerald-300",
    legalName: "VoltMart Electronics India LLP",
    trustScore: 95,
    slaHours: 36,
    currentBid: 870,
    rating: 4.8,
    city: "Noida",
    state: "Uttar Pradesh",
    isVerified: true,
    isoCertified: true,
    msmeRegistered: false,
    pastFulfillmentRate: 98.4,
    categories: ["Monitors", "IT Hardware", "Office Supplies"],
    minLeadTimeHours: 36,
    gstin: "07AABCV5519L1Z5",
    catalogUrl: "https://www.indiamart.com/voltmart-electronics",
    verifiedProof: "TrustSEAL Verified - Certified OEM Hardware Partner",
    contactEmail: "b2b@voltmartelectronics.in",
    contactPhone: "+91 120 689 4400",
    riskScore: 14,
    riskCategory: "LOW",
    riskLabel: "Low Risk",
    creditRating: "AA+",
    financialHealthScore: 93,
    operationalRiskScore: 12,
    complianceRiskScore: 9,
    gstFilingHealth: "100% Timely (24 Mo)",
    litigationCheck: "Zero Active Disputes"
  },
  {
    id: "ven_indotech_06",
    name: "IndoTech Global Sourcing",
    platform: "indiamart",
    platformLabel: "IndiaMART Leading Supplier",
    platformBadgeColor: "bg-emerald-100 text-emerald-800 border-emerald-300",
    legalName: "IndoTech Global Sourcing Ltd",
    trustScore: 94,
    slaHours: 48,
    currentBid: 880,
    rating: 4.7,
    city: "New Delhi",
    state: "Delhi NCR",
    isVerified: true,
    isoCertified: true,
    msmeRegistered: true,
    pastFulfillmentRate: 97.6,
    categories: ["Ergonomics", "Cables", "Keyboards"],
    minLeadTimeHours: 48,
    gstin: "07AAACI8834K1Z3",
    catalogUrl: "https://www.indiamart.com/indotech-sourcing",
    verifiedProof: "GST & Bank Verified Corporate Seller",
    contactEmail: "rfq@indotechglobal.in",
    contactPhone: "+91 11 4982 3000",
    riskScore: 18,
    riskCategory: "LOW",
    riskLabel: "Low Risk",
    creditRating: "AA",
    financialHealthScore: 89,
    operationalRiskScore: 16,
    complianceRiskScore: 11,
    gstFilingHealth: "98% Timely",
    litigationCheck: "Zero Disputes"
  },
  {
    id: "ven_shriram_07",
    name: "Shri Ram Precision Logistics",
    platform: "indiamart",
    platformLabel: "IndiaMART Certified MSME",
    platformBadgeColor: "bg-emerald-100 text-emerald-800 border-emerald-300",
    legalName: "Shri Ram Precision Commercial Corp",
    trustScore: 93,
    slaHours: 24,
    currentBid: 860,
    rating: 4.8,
    city: "Gurugram",
    state: "Haryana",
    isVerified: true,
    isoCertified: true,
    msmeRegistered: true,
    pastFulfillmentRate: 98.5,
    categories: ["IT Peripherals", "Accessories", "Workstation Parts"],
    minLeadTimeHours: 24,
    gstin: "06AABCS4491N1ZX",
    catalogUrl: "https://www.indiamart.com/shriram-precision",
    verifiedProof: "MSME Priority Supplier - 24hr Express Hub",
    contactEmail: "b2b@shriramprecision.com",
    contactPhone: "+91 124 492 8811",
    riskScore: 15,
    riskCategory: "LOW",
    riskLabel: "Low Risk",
    creditRating: "AA+",
    financialHealthScore: 91,
    operationalRiskScore: 14,
    complianceRiskScore: 8,
    gstFilingHealth: "100% Timely",
    litigationCheck: "Verified Clean"
  },
  {
    id: "ven_noida_ind_08",
    name: "Noida Industrial Peripheral Hub",
    platform: "indiamart",
    platformLabel: "IndiaMART Verified Distributor",
    platformBadgeColor: "bg-emerald-100 text-emerald-800 border-emerald-300",
    legalName: "Noida Industrial Distribution Network",
    trustScore: 91,
    slaHours: 48,
    currentBid: 895,
    rating: 4.6,
    city: "Greater Noida",
    state: "Uttar Pradesh",
    isVerified: true,
    isoCertified: false,
    msmeRegistered: true,
    pastFulfillmentRate: 96.9,
    categories: ["IT Hardware", "Cables", "Mounts"],
    minLeadTimeHours: 48,
    gstin: "09AABCN6612P1ZM",
    catalogUrl: "https://www.indiamart.com/noida-peripherals",
    verifiedProof: "Verified Bulk Distributor",
    contactEmail: "sales@noidaperipherals.in",
    contactPhone: "+91 120 234 9012",
    riskScore: 24,
    riskCategory: "MODERATE",
    riskLabel: "Moderate Risk",
    creditRating: "A",
    financialHealthScore: 84,
    operationalRiskScore: 22,
    complianceRiskScore: 16,
    gstFilingHealth: "96% Timely",
    litigationCheck: "Zero Active Disputes"
  },
  {
    id: "ven_apex_msme_09",
    name: "Apex MSME Enterprise Goods",
    platform: "indiamart",
    platformLabel: "IndiaMART TrustSEAL Platinum",
    platformBadgeColor: "bg-emerald-100 text-emerald-800 border-emerald-300",
    legalName: "Apex MSME Enterprise Solutions",
    trustScore: 96,
    slaHours: 24,
    currentBid: 845,
    rating: 4.9,
    city: "Pune",
    state: "Maharashtra",
    isVerified: true,
    isoCertified: true,
    msmeRegistered: true,
    pastFulfillmentRate: 99.0,
    categories: ["Ergonomics", "Keyboards", "Workstation Peripherals"],
    minLeadTimeHours: 24,
    gstin: "27AAACA9921D1Z1",
    catalogUrl: "https://www.indiamart.com/apex-msme",
    verifiedProof: "ISO 9001:2015 & E-Way Bill Express Clearance",
    contactEmail: "contracts@apexmsme.in",
    contactPhone: "+91 20 6711 4400",
    riskScore: 10,
    riskCategory: "VERY_LOW",
    riskLabel: "Tier-1 Low Risk",
    creditRating: "AAA",
    financialHealthScore: 96,
    operationalRiskScore: 8,
    complianceRiskScore: 5,
    gstFilingHealth: "100% Timely",
    litigationCheck: "Zero Disputes"
  },

  // --- Amazon Business Prime Suppliers ---
  {
    id: "ven_amazon_cloudtail_10",
    name: "Cloudtail B2B Enterprise Direct",
    platform: "amazon_business",
    platformLabel: "Amazon Business Prime OEM",
    platformBadgeColor: "bg-amber-100 text-amber-800 border-amber-300",
    legalName: "Cloudtail Commercial Retail Pvt Ltd",
    trustScore: 99,
    slaHours: 24,
    currentBid: 835,
    rating: 4.9,
    city: "Bengaluru",
    state: "Karnataka",
    isVerified: true,
    isoCertified: true,
    msmeRegistered: false,
    pastFulfillmentRate: 99.1,
    categories: ["IT Peripherals", "Ergonomics", "Monitors", "Keyboards"],
    minLeadTimeHours: 24,
    gstin: "29AABCC4412B1ZR",
    catalogUrl: "https://business.amazon.in/cloudtail-direct",
    verifiedProof: "Amazon Business Prime Verified • Automated GST ITC Invoicing",
    contactEmail: "b2b-prime@cloudtail.in",
    contactPhone: "+91 80 6199 0000",
    riskScore: 5,
    riskCategory: "VERY_LOW",
    riskLabel: "Tier-1 Low Risk",
    creditRating: "AAA",
    financialHealthScore: 99,
    operationalRiskScore: 3,
    complianceRiskScore: 2,
    gstFilingHealth: "100% Timely (60 Mo)",
    litigationCheck: "Zero Disputes"
  },
  {
    id: "ven_amazon_appario_11",
    name: "Appario Commercial Logistics",
    platform: "amazon_business",
    platformLabel: "Amazon Business Fulfilled",
    platformBadgeColor: "bg-amber-100 text-amber-800 border-amber-300",
    legalName: "Appario Retail Commercial Solutions",
    trustScore: 97,
    slaHours: 24,
    currentBid: 855,
    rating: 4.8,
    city: "Mumbai",
    state: "Maharashtra",
    isVerified: true,
    isoCertified: true,
    msmeRegistered: false,
    pastFulfillmentRate: 99.1,
    categories: ["Monitors", "Docking Stations", "Networking"],
    minLeadTimeHours: 24,
    gstin: "27AABCA7712M1Z0",
    catalogUrl: "https://business.amazon.in/appario-retail",
    verifiedProof: "Fulfilled by Amazon Business • Multi-Warehouse Stock",
    contactEmail: "enterprise@apparioretail.in",
    contactPhone: "+91 22 4192 7800",
    riskScore: 9,
    riskCategory: "VERY_LOW",
    riskLabel: "Tier-1 Low Risk",
    creditRating: "AAA",
    financialHealthScore: 96,
    operationalRiskScore: 7,
    complianceRiskScore: 5,
    gstFilingHealth: "100% Timely",
    litigationCheck: "Zero Disputes"
  },
  {
    id: "ven_swiftprocure_03",
    name: "SwiftProcure Systems",
    platform: "amazon_business",
    platformLabel: "Amazon Business Verified Seller",
    platformBadgeColor: "bg-amber-100 text-amber-800 border-amber-300",
    legalName: "SwiftProcure Rapid Systems Ltd",
    trustScore: 96,
    slaHours: 24,
    currentBid: 840,
    rating: 4.8,
    city: "Gurugram",
    state: "Haryana",
    isVerified: true,
    isoCertified: true,
    msmeRegistered: true,
    pastFulfillmentRate: 98.9,
    categories: ["Keyboards", "Ergonomics", "Cables"],
    minLeadTimeHours: 24,
    gstin: "06AAACS7721N1ZM",
    catalogUrl: "https://business.amazon.in/swiftprocure",
    verifiedProof: "Amazon Business Volume Discount Tier 1 Approved",
    contactEmail: "rfq@swiftprocuresystems.com",
    contactPhone: "+91 124 456 7890",
    riskScore: 11,
    riskCategory: "VERY_LOW",
    riskLabel: "Tier-1 Low Risk",
    creditRating: "AA+",
    financialHealthScore: 94,
    operationalRiskScore: 9,
    complianceRiskScore: 6,
    gstFilingHealth: "100% Timely",
    litigationCheck: "Zero Disputes"
  },
  {
    id: "ven_workstation_direct_12",
    name: "Workstation Direct B2B",
    platform: "amazon_business",
    platformLabel: "Amazon Business Tier-1",
    platformBadgeColor: "bg-amber-100 text-amber-800 border-amber-300",
    legalName: "Workstation Direct Wholesale India",
    trustScore: 95,
    slaHours: 36,
    currentBid: 865,
    rating: 4.7,
    city: "Hyderabad",
    state: "Telangana",
    isVerified: true,
    isoCertified: true,
    msmeRegistered: true,
    pastFulfillmentRate: 98.2,
    categories: ["Docking Stations", "Monitors", "Ergonomics"],
    minLeadTimeHours: 36,
    gstin: "36AABCW9912K1Z9",
    catalogUrl: "https://business.amazon.in/workstation-direct",
    verifiedProof: "Automated Tax Invoice & 30-Day B2B Credit Terms",
    contactEmail: "sales@workstationdirect.in",
    contactPhone: "+91 40 6821 5500",
    riskScore: 16,
    riskCategory: "LOW",
    riskLabel: "Low Risk",
    creditRating: "AA",
    financialHealthScore: 90,
    operationalRiskScore: 13,
    complianceRiskScore: 8,
    gstFilingHealth: "99% Timely",
    litigationCheck: "Zero Disputes"
  },

  // --- TradeIndia Verified Sourcing ---
  {
    id: "ven_gadgetzone_04",
    name: "GadgetZone Prime",
    platform: "tradeindia",
    platformLabel: "TradeIndia Trust Stamp",
    platformBadgeColor: "bg-blue-100 text-blue-800 border-blue-300",
    legalName: "GadgetZone Prime Commercial Corp",
    trustScore: 92,
    slaHours: 48,
    currentBid: 890,
    rating: 4.7,
    city: "Pune",
    state: "Maharashtra",
    isVerified: true,
    isoCertified: true,
    msmeRegistered: true,
    pastFulfillmentRate: 97.8,
    categories: ["Docking Stations", "Peripherals", "Hubs"],
    minLeadTimeHours: 48,
    gstin: "27AAACG4412P1ZK",
    catalogUrl: "https://www.tradeindia.com/Seller-GadgetZone-Prime",
    verifiedProof: "TradeIndia Trust Stamp & Super Seller Verified",
    contactEmail: "sales@gadgetzoneprime.in",
    contactPhone: "+91 20 2749 5500",
    riskScore: 19,
    riskCategory: "LOW",
    riskLabel: "Low Risk",
    creditRating: "AA",
    financialHealthScore: 88,
    operationalRiskScore: 18,
    complianceRiskScore: 10,
    gstFilingHealth: "98% Timely",
    litigationCheck: "Zero Disputes"
  },
  {
    id: "ven_nexus_05",
    name: "Nexus Industrial",
    platform: "tradeindia",
    platformLabel: "TradeIndia Verified Exporter",
    platformBadgeColor: "bg-blue-100 text-blue-800 border-blue-300",
    legalName: "Nexus Industrial Wholesale Solutions",
    trustScore: 94,
    slaHours: 36,
    currentBid: 865,
    rating: 4.8,
    city: "Chennai",
    state: "Tamil Nadu",
    isVerified: true,
    isoCertified: true,
    msmeRegistered: true,
    pastFulfillmentRate: 98.2,
    totalTransactions: 2431,
    contractValueCr: 4.2,
    categories: ["Headsets", "Audio", "Industrial IT"],
    minLeadTimeHours: 36,
    gstin: "33AABCN3391C1ZT",
    catalogUrl: "https://www.tradeindia.com/Seller-Nexus-Industrial",
    verifiedProof: "TradeIndia Verified Star Exporter • MSME Certified",
    contactEmail: "orders@nexusindustrial.org",
    contactPhone: "+91 44 2811 0932",
    riskScore: 17,
    riskCategory: "LOW",
    riskLabel: "Low Risk",
    creditRating: "AA",
    financialHealthScore: 90,
    operationalRiskScore: 15,
    complianceRiskScore: 9,
    gstFilingHealth: "100% Timely",
    litigationCheck: "Zero Disputes"
  },
  {
    id: "ven_bharat_heavy_13",
    name: "Bharat Heavy IT Distribution",
    platform: "tradeindia",
    platformLabel: "TradeIndia Certified Supplier",
    platformBadgeColor: "bg-blue-100 text-blue-800 border-blue-300",
    legalName: "Bharat Heavy Distribution Pvt Ltd",
    trustScore: 93,
    slaHours: 48,
    currentBid: 875,
    rating: 4.7,
    city: "Ahmedabad",
    state: "Gujarat",
    isVerified: true,
    isoCertified: true,
    msmeRegistered: true,
    pastFulfillmentRate: 97.4,
    categories: ["Networking", "Cables", "Server Racks"],
    minLeadTimeHours: 48,
    gstin: "24AABCB3391D1Z8",
    catalogUrl: "https://www.tradeindia.com/Seller-Bharat-Heavy-IT",
    verifiedProof: "ISO 9001 Certified Exporter",
    contactEmail: "info@bharatheavyit.com",
    contactPhone: "+91 79 4912 3300",
    riskScore: 21,
    riskCategory: "MODERATE",
    riskLabel: "Moderate Risk",
    creditRating: "A+",
    financialHealthScore: 86,
    operationalRiskScore: 20,
    complianceRiskScore: 12,
    gstFilingHealth: "97% Timely",
    litigationCheck: "Zero Active Disputes"
  },
  {
    id: "ven_vardhman_14",
    name: "Vardhman Enterprise Tools",
    platform: "tradeindia",
    platformLabel: "TradeIndia Verified Member",
    platformBadgeColor: "bg-blue-100 text-blue-800 border-blue-300",
    legalName: "Vardhman Commercial Tools LLP",
    trustScore: 90,
    slaHours: 48,
    currentBid: 895,
    rating: 4.6,
    city: "Kolkata",
    state: "West Bengal",
    isVerified: true,
    isoCertified: false,
    msmeRegistered: true,
    pastFulfillmentRate: 96.8,
    categories: ["Ergonomics", "Furniture", "Accessories"],
    minLeadTimeHours: 48,
    gstin: "19AABCV2219K1Z4",
    catalogUrl: "https://www.tradeindia.com/Seller-Vardhman-Tools",
    verifiedProof: "Verified MSME Eastern Corridor Hub",
    contactEmail: "contact@vardhmantools.co.in",
    contactPhone: "+91 33 2289 4411",
    riskScore: 26,
    riskCategory: "MODERATE",
    riskLabel: "Moderate Risk",
    creditRating: "A",
    financialHealthScore: 82,
    operationalRiskScore: 24,
    complianceRiskScore: 18,
    gstFilingHealth: "95% Timely",
    litigationCheck: "Zero Disputes"
  },

  // --- Alibaba Global Trade Assurance ---
  {
    id: "ven_alibaba_kingspec_15",
    name: "Shenzhen KingSpec Ergonomics Co.",
    platform: "alibaba",
    platformLabel: "Alibaba 8-Yr Gold Supplier",
    platformBadgeColor: "bg-orange-100 text-orange-800 border-orange-300",
    legalName: "Shenzhen KingSpec Technology Co. Ltd",
    trustScore: 96,
    slaHours: 72,
    currentBid: 780,
    rating: 4.9,
    city: "Shenzhen",
    state: "Guangdong, China",
    isVerified: true,
    isoCertified: true,
    msmeRegistered: false,
    pastFulfillmentRate: 99.4,
    categories: ["Ergonomics", "Keyboards", "Memory Foam Parts"],
    minLeadTimeHours: 72,
    tradeLicense: "CN-9144030079172348",
    catalogUrl: "https://kingspec.en.alibaba.com",
    verifiedProof: "Alibaba Trade Assurance $500,000 Guarantee • Verified Customizer",
    contactEmail: "global@kingspec-ergo.com",
    contactPhone: "+86 755 2812 9900",
    riskScore: 18,
    riskCategory: "LOW",
    riskLabel: "Trade Assurance Backed",
    creditRating: "AAA",
    financialHealthScore: 95,
    operationalRiskScore: 22,
    complianceRiskScore: 7,
    gstFilingHealth: "Customs Verified (IEC)",
    litigationCheck: "Trade Assurance Guarantee Active"
  },
  {
    id: "ven_alibaba_hangzhou_16",
    name: "Hangzhou Ergotech Precision",
    platform: "alibaba",
    platformLabel: "Alibaba Verified Customizer",
    platformBadgeColor: "bg-orange-100 text-orange-800 border-orange-300",
    legalName: "Hangzhou Ergotech Manufacturing Ltd",
    trustScore: 95,
    slaHours: 72,
    currentBid: 795,
    rating: 4.8,
    city: "Hangzhou",
    state: "Zhejiang, China",
    isVerified: true,
    isoCertified: true,
    msmeRegistered: false,
    pastFulfillmentRate: 98.8,
    categories: ["Ergonomic Wrist Rests", "Monitor Arms", "Desk Hubs"],
    minLeadTimeHours: 72,
    tradeLicense: "CN-9133010078921832",
    catalogUrl: "https://ergotech.en.alibaba.com",
    verifiedProof: "Trade Assurance Verified • SGS Onsite Inspection Passed",
    contactEmail: "sales@ergotech-hangzhou.cn",
    contactPhone: "+86 571 8812 7700",
    riskScore: 20,
    riskCategory: "LOW",
    riskLabel: "SGS Onsite Audited",
    creditRating: "AA+",
    financialHealthScore: 92,
    operationalRiskScore: 24,
    complianceRiskScore: 8,
    gstFilingHealth: "Customs Verified (IEC)",
    litigationCheck: "Clean Inspection Record"
  },
  {
    id: "ven_alibaba_dongguan_17",
    name: "Dongguan Precision Peripherals",
    platform: "alibaba",
    platformLabel: "Alibaba 5-Yr Gold Supplier",
    platformBadgeColor: "bg-orange-100 text-orange-800 border-orange-300",
    legalName: "Dongguan Precision Peripherals Ltd",
    trustScore: 94,
    slaHours: 72,
    currentBid: 810,
    rating: 4.7,
    city: "Dongguan",
    state: "Guangdong, China",
    isVerified: true,
    isoCertified: true,
    msmeRegistered: false,
    pastFulfillmentRate: 98.1,
    categories: ["Cables", "Keyboards", "Docking Stations"],
    minLeadTimeHours: 72,
    tradeLicense: "CN-9144190069213452",
    catalogUrl: "https://dgprecision.en.alibaba.com",
    verifiedProof: "Trade Assurance • CE, FCC, RoHS Certified",
    contactEmail: "export@dgprecision.com",
    contactPhone: "+86 769 8552 1100",
    riskScore: 22,
    riskCategory: "MODERATE",
    riskLabel: "Moderate Risk",
    creditRating: "AA",
    financialHealthScore: 89,
    operationalRiskScore: 25,
    complianceRiskScore: 10,
    gstFilingHealth: "Customs Verified (IEC)",
    litigationCheck: "Zero Active Disputes"
  },
  {
    id: "ven_alibaba_guangzhou_18",
    name: "Guangzhou Apex Hardware Corp",
    platform: "alibaba",
    platformLabel: "Alibaba Verified Manufacturer",
    platformBadgeColor: "bg-orange-100 text-orange-800 border-orange-300",
    legalName: "Guangzhou Apex Commercial Hardware Co.",
    trustScore: 93,
    slaHours: 72,
    currentBid: 820,
    rating: 4.7,
    city: "Guangzhou",
    state: "Guangdong, China",
    isVerified: true,
    isoCertified: true,
    msmeRegistered: false,
    pastFulfillmentRate: 97.9,
    categories: ["Monitors", "Headsets", "Commercial Displays"],
    minLeadTimeHours: 72,
    tradeLicense: "CN-9144010168329918",
    catalogUrl: "https://apexguangzhou.en.alibaba.com",
    verifiedProof: "TUV Rheinland Verified Supplier Certificate",
    contactEmail: "orders@apexguangzhou.com",
    contactPhone: "+86 20 3891 4400",
    riskScore: 25,
    riskCategory: "MODERATE",
    riskLabel: "Moderate Risk",
    creditRating: "AA-",
    financialHealthScore: 87,
    operationalRiskScore: 26,
    complianceRiskScore: 11,
    gstFilingHealth: "Customs Verified (IEC)",
    litigationCheck: "TUV Audited"
  }
];
